import {MuseumWorld} from '../../js/world.js?v=entry-feedback-2';
import {startIntroTitle,finishIntroTitle} from '../../js/title.js?v=title-c-1';
const $=id=>document.getElementById(id),query=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');
const tiltLimit=3*Math.PI/180;
let world,variant='a',busy=false,epoch=0,tilt=0,tiltAnimation=null,completedView=null,reduced=query.matches;
function setReduced(value){reduced=value;document.body.classList.toggle('reduce-motion',value);$('motion').setAttribute('aria-pressed',String(value));$('motion').textContent=value?'動態已減少':'減少動態';if(world){world.reduced=value;reset();}if(value)finishIntroTitle();}
function reset(){epoch++;busy=false;tiltAnimation?.resolve(false);tiltAnimation=null;tilt=0;completedView=null;world?.resetEntryApproach();world?.pause(false);if(world?.entryFilm){world.entryFilm.mesh.scale.setScalar(1);world.entryFilm.elapsed=0;world.entryFilm.last=0;world.disturbEntryFilm(0);world.invalidate();}$('veil').classList.remove('active');document.querySelector('.after-fade').hidden=true;$('enter').removeAttribute('aria-busy');$('comparison-status').textContent='Hover 只前移；點「進入展覽」比較同步前移與抬頭的感覺。';}
function feedback(amount,duration=1000){if(!busy&&!reduced&&world)world.approachEntry(amount,duration);}
$('enter').addEventListener('pointerenter',()=>{if(fine.matches)feedback(1.8);});$('enter').addEventListener('pointerleave',()=>feedback(0,800));$('enter').addEventListener('pointercancel',()=>feedback(0,800));$('enter').addEventListener('focus',()=>{if(fine.matches&&$('enter').matches(':focus-visible'))feedback(1.8);});$('enter').addEventListener('blur',()=>feedback(0,800));
$('enter').onclick=async()=>{if(!world||busy)return;busy=true;const generation=++epoch;$('enter').setAttribute('aria-busy','true');finishIntroTitle();world.entryFilm.elapsed=0;world.entryFilm.last=0;world.disturbEntryFilm(0);const lifted=variant==='b'&&!reduced?new Promise(resolve=>{tiltAnimation={start:performance.now(),delay:0,duration:1250,resolve};}):Promise.resolve(true);$('comparison-status').textContent=variant==='b'?'同步前移與緩慢上仰 3°，再停住淡出。':'只前移，朝向保持穩定。';const complete=reduced||(await Promise.all([world.approachEntry(4.5,1250),lifted])).every(Boolean);if(generation!==epoch||!complete)return;if(!reduced){world.invalidate();await new Promise(r=>setTimeout(r,160));}if(generation!==epoch||document.hidden)return;completedView={offset:world.entryOffset,scale:world.entryFilm.mesh.scale.x,tiltDegrees:tilt*180/Math.PI,yaw:world.yaw};$('veil').classList.add('active');await new Promise(r=>setTimeout(r,reduced?0:250));if(generation!==epoch)return;world.pause(true);document.querySelector('.after-fade').hidden=false;$('comparison-status').textContent='完成。可切換版本，或按「再看一次」。';$('enter').removeAttribute('aria-busy');};
for(const button of document.querySelectorAll('[data-variant]'))button.onclick=()=>{variant=button.dataset.variant;reset();for(const b of document.querySelectorAll('[data-variant]'))b.setAttribute('aria-pressed',String(b===button));$('variant-description').textContent=variant==='a'?'只有鏡頭前移，朝向與碟片尺寸保持不變。':'Hover 同 A；click 同步前移與上仰 3°。兩版都不放大碟片。';};
$('reset').onclick=reset;$('replay').onclick=()=>{reset();$('enter').focus({preventScroll:true});};$('motion').onclick=()=>setReduced(!reduced);query.addEventListener('change',e=>setReduced(e.matches));setReduced(reduced);
document.addEventListener('visibilitychange',()=>{if(document.hidden){reset();world?.pause(true);}else world?.pause(false);});
try{const response=await fetch('../../exhibition.json');if(!response.ok)throw Error('展覽資料載入失敗');const ex=await response.json();world=new MuseumWorld($('world'),ex,{reduced,onWork:()=>{},onStation:()=>{},onPortal:()=>{},onReady:()=>{$('status').textContent='真實入口場景 · 此頁只比較動效，不進入展廳。';},onFailure:message=>{$('status').textContent=message;$('enter').disabled=true;},onFrame:()=>{if(!tiltAnimation)return;const t=Math.max(0,Math.min(1,(performance.now()-tiltAnimation.start-tiltAnimation.delay)/tiltAnimation.duration)),u=t*t*(3-2*t);tilt=tiltLimit*u;if(t===1){const complete=tiltAnimation.resolve;tiltAnimation=null;complete(true);}}});
 // Study-only view rotation: the forward path and museum's source remain unchanged.
 const render=world.renderer.render.bind(world.renderer);world.renderer.render=(scene,camera)=>{camera.rotation.x+=tilt;camera.updateMatrixWorld();render(scene,camera);};
 Object.defineProperty(window,'cameraStudy',{get:()=>({variant,busy,completedView,scale:world.entryFilm?.mesh.scale.x,offset:world.entryOffset,tiltDegrees:tilt*180/Math.PI,basePitch:world.pitch,cameraPitch:world.camera.rotation.x,yaw:world.yaw,moving:!!world.entryApproach,lifting:!!tiltAnimation,textures:world.renderer.info.memory.textures,geometries:world.renderer.info.memory.geometries,scheduled:!!world.raf})});startIntroTitle(()=>reduced);}catch(error){$('status').textContent=error.message;$('enter').disabled=true;}
