const $=id=>document.getElementById(id);
const reduceQuery=matchMedia('(prefers-reduced-motion: reduce)');
let reduced=reduceQuery.matches,ex,world=null,current=0,station=0,selected=null,viewerReturn=null,viewerWork=null,loadTimer,frameGeneration=0,tour=null,tourRAF=null,transitionGeneration=0,moveGeneration=0,filter=0;
let cardAnimation=null,cardEpoch=0,focusGeneration=0;
const dialogMotion=new Map();
const exhibitionText='形狀如何共處，規則如何產生秩序，材料如何留下時間？這座漂浮在暮色中的館，讓五個展廳各自遵守不同的空間規則。從測量的薄屏、共處的色面，到生長的標本與交疊的曝光，最後在一張接近消失的膜前停下。世界不必先對齊，關係也能慢慢形成。';
function setReduced(value){reduced=value;document.body.classList.toggle("reduce-motion",value);if(value&&cardAnimation)cardAnimation.finish();if(value)for(const state of dialogMotion.values())state.animation?.finish();if(world){world.reduced=value;if(world.membrane)world.membrane.last=0;world.invalidate();}$('motion').setAttribute('aria-pressed',String(value));$('motion').textContent=value?'動態已減少':'減少動態';}
setReduced(reduced);reduceQuery.addEventListener('change',e=>setReduced(e.matches));$('motion').onclick=()=>setReduced(!reduced);
async function closeDialog(d){
 if(!d.open)return;
 const previous=dialogMotion.get(d);if(previous?.closing)return previous.done;
 const from={opacity:getComputedStyle(d).opacity,transform:getComputedStyle(d).transform};previous?.animation?.cancel();
 const state={closing:true,animation:null,done:null};dialogMotion.set(d,state);d.dataset.state='closing';d.inert=true;
 if(reduced){d.close();d.inert=false;d.dataset.state='closed';dialogMotion.delete(d);return;}
 const animation=d.animate([from,{opacity:0,transform:'translateY(10px) scale(.992)'}],{duration:180,easing:'cubic-bezier(.4,0,.8,.2)',fill:'both'});state.animation=animation;
 state.done=animation.finished.catch(()=>{}).then(()=>{if(dialogMotion.get(d)!==state)return;d.close();d.inert=false;d.dataset.state='closed';animation.cancel();dialogMotion.delete(d);});return state.done;
}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDialog(b.closest('dialog')));
document.querySelectorAll('dialog:not(#viewer)').forEach(d=>{
 d.addEventListener('cancel',e=>{e.preventDefault();closeDialog(d);});
 d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d);}});
});
function showDialog(id){
 pauseTour();const d=$(id),previous=dialogMotion.get(d);if(d.open&&!previous?.closing)return;previous?.animation?.cancel();
 const state={closing:false,animation:null};dialogMotion.set(d,state);d.inert=false;if(!d.open)d.showModal();d.dataset.state='opening';
 if(reduced){d.dataset.state='open';dialogMotion.delete(d);return;}
 const animation=d.animate([{opacity:0,transform:'translateY(18px) scale(.985)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:260,easing:'cubic-bezier(.22,1,.36,1)',fill:'both'});state.animation=animation;
 animation.finished.catch(()=>{}).then(()=>{if(dialogMotion.get(d)!==state)return;animation.cancel();d.dataset.state='open';dialogMotion.delete(d);});
}
function showAbout(section=0){const s=ex?.sections.find(s=>s.id===section);$('about-title').textContent=s?s.name:ex?.title||'世界尚未對齊';$('about-eyebrow').textContent=s?`0${s.id}　／　${s.en.toUpperCase()}`:'CURATORIAL NOTE　／　首展';$('about-text').textContent=s?s.text:exhibitionText;showDialog('about-dialog');}
$('about-button').onclick=()=>showAbout();$('chapter-name').onclick=()=>showAbout(current);$('help-button').onclick=()=>showDialog('help-dialog');$('map-button').onclick=()=>showDialog('map-dialog');$('list-button').onclick=()=>showDialog('catalog-dialog');$('intro-tour').onclick=()=>startTour();$('tour-start').onclick=()=>startTour();$('enter').onclick=()=>changeRoom(1);$('home').onclick=()=>{exitTour();changeRoom(0);};$('card-close').onclick=()=>hideCard();$('stop-label').onclick=()=>{if(world?.stations[station]?.work)focusWork(world.stations[station].work);else showAbout(current);};$('open-work').onclick=()=>selected&&openViewer(selected);
$('previous-stop').onclick=()=>goStation(station-1);$('next-stop').onclick=()=>goStation(station+1);
$('ending-home').onclick=()=>{exitTour();changeRoom(0);};$('ending-continue').onclick=()=>{exitTour();changeRoom(1);};$('ending-list').onclick=()=>showDialog('catalog-dialog');
function buildUI(){
 $('map-rooms').replaceChildren();for(const s of ex.sections){const b=document.createElement('button');b.className='map-room';b.innerHTML=`<i>0${s.id}</i><span><b>${s.name}</b><small>${s.en}　·　${ex.works.filter(w=>w.section===s.id).length} 件</small></span><span class="map-arrow">↗</span>`;b.onclick=async()=>{await closeDialog($('map-dialog'));exitTour();changeRoom(s.id);};$('map-rooms').append(b);}
 for(const s of [{id:0,name:'全部 35'},...ex.sections]){const b=document.createElement('button');b.textContent=s.id?`0${s.id} ${s.name}`:s.name;b.dataset.section=s.id;b.setAttribute('aria-pressed',String(!s.id));b.onclick=()=>{filter=s.id;renderCatalog();};$('filters').append(b);}
 renderCatalog();$('search').oninput=renderCatalog;
}
function renderCatalog(){if(!ex)return;const q=$('search').value.trim().toLowerCase();$('catalog').replaceChildren();let count=0;for(const w of ex.works){const s=ex.sections[w.section-1];if(filter&&w.section!==filter||q&&!`${w.name} ${w.en} ${w.series} ${s.name} ${w.summary}`.toLowerCase().includes(q))continue;count++;const a=document.createElement('article');a.className='catalog-work';a.innerHTML=`<img src="${w.preview}" alt="${w.name}：原作品靜態停格" loading="lazy" width="720" height="450"><h3>${w.name}</h3><p class="meta">0${w.section} ${s.name}　／　${w.series==='p5-demos2'?'p5.js':'GLSL'}</p><button type="button">前往展品 ↗</button><a href="${w.entry}" target="_blank" rel="noopener">原作品</a>`;a.querySelector('button').onclick=async()=>{await closeDialog($('catalog-dialog'));exitTour();if(!world){openViewer(w);return;}if(current!==w.section)await changeRoom(w.section);focusWork(w);};$('catalog').append(a);}
 $('empty').hidden=count!==0;document.querySelectorAll('#filters button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.section)===filter)));
}
function setLabelState(id=null){for(const {button,work} of world?.labels||[]){const open=work.id===id;button.classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',`${open?'收起作品資訊':'靠近作品'}：${work.name}`);button.querySelector('.arrow').textContent=open?'−':'↗';}world?.invalidate();}
async function hideCard({immediate=false,clearSelection=true}={}){if(clearSelection){focusGeneration++;selected=null;}setLabelState();const epoch=++cardEpoch,card=$('work-card'),style=getComputedStyle(card),from={opacity:style.opacity,transform:style.transform};cardAnimation?.cancel();cardAnimation=null;card.inert=true;card.setAttribute('aria-hidden','true');if(card.hidden||immediate||reduced){card.hidden=true;card.dataset.state='closed';return;}card.dataset.state='closing';const a=card.animate([from,{opacity:0,transform:'translateY(8px) scale(.992)'}],{duration:170,easing:'cubic-bezier(.4,0,.8,.2)',fill:'both'});cardAnimation=a;await a.finished.catch(()=>{});if(epoch!==cardEpoch)return;card.hidden=true;card.dataset.state='closed';a.cancel();cardAnimation=null;}
function showCard(){const epoch=++cardEpoch;cardAnimation?.cancel();const card=$('work-card');card.hidden=false;card.inert=false;card.removeAttribute('aria-hidden');card.dataset.state='opening';setLabelState(selected?.id);if(reduced){cardAnimation=null;card.dataset.state='open';return;}const a=card.animate([{opacity:0,transform:'translateX(calc(100% + 48px))'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:360,easing:'cubic-bezier(.22,1,.36,1)',fill:'both'});cardAnimation=a;a.finished.catch(()=>{}).then(()=>{if(epoch!==cardEpoch)return;a.cancel();cardAnimation=null;card.dataset.state='open';world?.invalidate();});}
function updateChrome(){const entered=current>0;document.body.classList.toggle('entered',entered);$('intro').hidden=entered;$('chapter').hidden=!entered;$('room-controls').hidden=!entered||!!tour;$('footer-controls').hidden=!entered;$('coordinates').hidden=entered;hideCard({immediate:true});$('ending').hidden=true;$('threshold').hidden=true;
 if(entered){const s=ex.sections[current-1];$('chapter-number').textContent=`0${current} / 05　·　${s.anomaly}`;$('chapter-name').textContent=s.name;$('chapter-rule').textContent=s.rule;$('hint').textContent='拖曳環顧　·　點地面前進　·　點作品靠近';}else $('hint').textContent='35 件作品　·　5 個展區　·　按自己的節奏';
}
async function changeRoom(id,{portal=false}={}){if(!world){filter=id;renderCatalog();showDialog('catalog-dialog');return;}moveGeneration++;const gen=++transitionGeneration;$('veil').classList.add('active');await new Promise(r=>setTimeout(r,reduced?0:230));if(gen!==transitionGeneration)return;current=id;station=0;world.build(id);if(portal)world.enterPortal();updateChrome();updateStation();world.invalidate();await new Promise(r=>setTimeout(r,reduced?0:80));if(gen===transitionGeneration)$('veil').classList.remove('active');$('world').focus({preventScroll:true});}
function updateStation(){if(!world||!current)return;const s=world.stations[station];$('stop-label').textContent=s?.name||'展廳入口';$('previous-stop').disabled=current===1&&station===0;$('next-stop').textContent=station===world.stations.length-1?(current===5?'↺':'↗'):'→';const atExit=station===world.stations.length-1&&current<5,next=ex.sections[current];$('threshold').hidden=!atExit;$('room-controls').classList.toggle('at-threshold',atExit);if(atExit){$('threshold-number').textContent=`下一廳　／　0${next.id}　·　空間一瞥`;$('threshold-name').textContent=next.name;$('threshold-text').textContent=ex.sections[current-1].exitText;$('next-stop').textContent=`前往${next.name} ↗`;} $('next-stop').setAttribute('aria-label',station===world.stations.length-1?(current===5?'返回第一展區':`前往${next.name}`):'下一個觀看位置');}
async function goStation(index,{fromTour=false}={}){if(!world||!current)return;if(!fromTour)pauseTour();if(index<0){if(current>1)await changeRoom(current-1);return;}if(index>=world.stations.length){if(current<5)await changeRoom(current+1);else{exitTour();await changeRoom(1);}return;}station=index;const s=world.stations[index];hideCard();await comfortMove(s.pos,s.look);updateStation();if(current===5&&index===world.stations.length-1)$('ending').hidden=false;else $('ending').hidden=true;}
async function comfortMove(pos,look){const gen=++moveGeneration;const distance=world.position.distanceTo({x:pos[0],y:pos[1],z:pos[2]});if((distance>8||current===2&&distance>1)&&!reduced){world.animation=null;$('veil').classList.add('active');await new Promise(r=>setTimeout(r,220));if(gen!==moveGeneration||!world)return;world.position.fromArray(pos);world.lookAt(look);world.invalidate();$('veil').classList.remove('active');}else world.move(pos,look);}
async function focusWork(w,{fromTour=false}={}){if(!world){openViewer(w);return;}if(!fromTour)pauseTour();const request=++focusGeneration;await hideCard({clearSelection:false});if(request!==focusGeneration)return;selected=w;station=world.stations.findIndex(s=>s.work?.id===w.id);const view=world.viewFor(w);await comfortMove(view.pos,view.look);if(current!==w.section||selected?.id!==w.id)return;$('work-series').textContent=`0${w.section}　／　${w.series==='p5-demos2'?'規則之後 · p5.js':'慢物質 · GLSL'}`;$('work-name').textContent=w.name;$('work-en').textContent=w.en;$('work-summary').textContent=w.summary;showCard();$('ending').hidden=true;updateStation();}
function stopFrame(){clearTimeout(loadTimer);frameGeneration++;const frame=$('frame-host').querySelector('iframe');if(frame){frame.src='about:blank';frame.remove();}$('frame-host').replaceChildren();}
function openViewer(w,{keepReturn=false}={}){pauseTour();if(!keepReturn)viewerReturn=world?.snapshot()||null;viewerWork=w;stopFrame();$('viewer-title').textContent=w.name;$('original-link').href=w.entry;$('viewer-preview').src=w.preview;$('viewer-preview').alt=`${w.name}：原作品靜態停格`;$('viewer-preview').hidden=false;$('viewer-status').hidden=false;$('viewer-status').textContent='正在載入原作品…';$('viewer-error').hidden=true;if(!$('viewer').open)$('viewer').showModal();world?.pause(true);loadFrame(w);}
function loadFrame(w){const gen=frameGeneration;const f=document.createElement('iframe');f.title=`${w.name} — 原作品即時互動`;f.setAttribute('sandbox','allow-scripts allow-same-origin allow-downloads');f.src=w.entry;f.onload=()=>{if(gen!==frameGeneration)return;clearTimeout(loadTimer);try{const doc=f.contentDocument;if(!doc||!doc.querySelector('canvas')){viewerFailed('作品未能完成載入。');return;}$('viewer-status').hidden=true;$('viewer-preview').hidden=true;doc.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const url=new URL(a.href);if(url.origin!==location.origin)return;const next=ex.works.find(n=>new URL(n.source,location.href).pathname===url.pathname);e.preventDefault();if(next)openViewer(next,{keepReturn:true});else closeViewer();});
 // The parent observes original fallback UI without changing the original pages.
 const failure=()=>{if(gen!==frameGeneration||!f.isConnected)return;const node=doc.querySelector('#fallback');if(node){const style=f.contentWindow.getComputedStyle(node);if(style.display!=='none'&&style.visibility!=='hidden'&&!node.hidden)viewerFailed('原作品的繪圖環境無法啟動。');}};failure();new f.contentWindow.MutationObserver(failure).observe(doc.body,{subtree:true,attributes:true,attributeFilter:['hidden','class','style']});
 }catch(_){viewerFailed('作品載入未能確認。');}};f.onerror=()=>{if(gen===frameGeneration)viewerFailed('原作品載入失敗。');};$('frame-host').append(f);loadTimer=setTimeout(()=>{if(gen===frameGeneration&&!$('viewer-status').hidden)viewerFailed('作品載入逾時。');},15000);}
function viewerFailed(message){$('viewer-status').hidden=true;$('viewer-error').hidden=false;$('viewer-error p').textContent=`${message} 可以返回展間或開啟原作品頁。`;}
function closeViewer(){stopFrame();$('viewer').close();if(world){if(viewerReturn)world.restore(viewerReturn);world.pause(false);}(world?$('open-work'):$('list-button')).focus({preventScroll:true});viewerWork=null;}
$('viewer-close').onclick=closeViewer;$('viewer').addEventListener('cancel',e=>{e.preventDefault();closeViewer();});$('viewer-retry').onclick=()=>viewerWork&&openViewer(viewerWork,{keepReturn:true});
const itinerary=[{section:1,slug:'flow-field',text:'讓線條先替我們找路。'},{section:1,slug:'boids-flocking',text:'沒有領袖，方向仍會浮現。'},{section:2,slug:'negotiated-territories',text:'每一次取得空間，也是一次退讓。'},{section:2,slug:'within-the-same-frame',text:'門後還有門：局部改變整體的尺度。'},{section:3,slug:'differential-growth',text:'生命以一條線，記住時間。'},{section:3,slug:'organic-growth',text:'石面也是一個緩慢的世界。'},{section:4,slug:'noise-dissolve',text:'影像交換彼此的記憶。'},{section:4,slug:'long-exposure',text:'我們看見的，是等待留下的路。'},{section:5,slug:'textile-moire',text:'兩個平面之間，浮出第三種關係。'},{section:5,slug:'thin-film',text:'薄到接近消失時，光顯出厚度。'}];
async function startTour(){if(!world){showDialog('catalog-dialog');return;}exitTour();tour={index:0,paused:false,elapsed:0,last:performance.now(),busy:false};$('tourbar').hidden=false;$('room-controls').hidden=true;await visitTourStop();tourTick(performance.now());}
async function visitTourStop(){if(!tour)return;const t=tour,stop=itinerary[t.index];t.busy=true;if(current!==stop.section)await changeRoom(stop.section);if(tour!==t)return;const work=ex.works.find(w=>w.slug===stop.slug);focusWork(work,{fromTour:true});$('tour-text').textContent=`${String(t.index+1).padStart(2,'0')} / 10　${stop.text}`;$('tour-pause').textContent=t.paused?'繼續':'暫停';t.elapsed=0;t.last=performance.now();t.busy=false;}
function tourTick(now){tourRAF=null;if(!tour)return;const t=tour;if(!t.paused&&!t.busy&&!document.hidden){t.elapsed+=Math.min(now-t.last,100);$('tour-progress').style.width=`${Math.min(t.elapsed/16000,1)*100}%`;if(t.elapsed>16000)nextTour();}t.last=now;if(!document.hidden&&!t.paused)tourRAF=requestAnimationFrame(tourTick);}
function pauseTour(){if(tour){tour.paused=true;cancelAnimationFrame(tourRAF);tourRAF=null;$('tour-pause').textContent='繼續';}}
function exitTour(){cancelAnimationFrame(tourRAF);tourRAF=null;tour=null;$('tourbar').hidden=true;$('room-controls').hidden=current===0||!world;}
async function nextTour(){if(!tour||tour.busy)return;if(tour.index===itinerary.length-1){exitTour();hideCard();$('ending').hidden=false;return;}tour.index++;await visitTourStop();}
$('tour-pause').onclick=()=>{if(!tour)return;tour.paused=!tour.paused;tour.last=performance.now();$('tour-pause').textContent=tour.paused?'繼續':'暫停';if(tour.paused){cancelAnimationFrame(tourRAF);tourRAF=null;}else if(!tourRAF)tourTick(tour.last);};$('tour-next').onclick=()=>nextTour();$('tour-exit').onclick=exitTour;$('world').addEventListener('pointerdown',pauseTour);
document.addEventListener('visibilitychange',()=>{world?.pause(document.hidden||$('viewer').open);if(document.hidden){cancelAnimationFrame(tourRAF);tourRAF=null;}else{if(tour){tour.last=performance.now();tourTick(tour.last);}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){hideCard();pauseTour();}});
function fallback(reason){moveGeneration++;transitionGeneration++;$('veil').classList.remove('active');world?.shutdown();world=null;current=0;station=0;exitTour();updateChrome();$('work-card').hidden=true;document.body.classList.add('fallback');$('loading-preview').hidden=false;$('status').textContent=reason+' 所有 35 件作品可從目錄觀看。';$('enter').textContent='以作品目錄參觀 ↗';$('enter').onclick=()=>showDialog('catalog-dialog');$('intro-tour').hidden=true;$('room-controls').hidden=true;$('chapter').hidden=true;world=null;}
async function boot(){try{const response=await fetch('exhibition.json');if(!response.ok)throw Error('資料未能載入');ex=await response.json();buildUI();if(new URLSearchParams(location.search).has('flat')){fallback('已切換為平面觀看模式。');return;}
 const {MuseumWorld}=await import('./world.js?v=card-motion-1');world=new MuseumWorld($('world'),ex,{onWork:w=>{if(selected?.id===w.id&&!$('work-card').hidden&&!$('work-card').inert)hideCard();else focusWork(w);},onStation:goStation,onPortal:()=>{},onReady:()=>{$('loading-preview').hidden=true;$('status').textContent='展覽已就緒　／　約 3 分鐘導覽，可隨時停留';},onFailure:fallback,reduced});
 // A read-only snapshot assists repeatable local QA and never starts artwork contexts.
 Object.defineProperty(window,'intervalState',{get:()=>({current,station,selected:selected?.id,viewer:viewerWork?.id,position:world?.snapshot(),tour:tour?{index:tour.index,paused:tour.paused}:null,render:world?{pending:world.pendingTextures,textures:world.renderer.info.memory.textures,geometries:world.renderer.info.memory.geometries,calls:world.renderer.info.render.calls,scheduled:!!world.raf,moving:!!world.animation,ambient:world.ambientActive(),membraneTime:world.membrane?.elapsed??null}:null})});
 }catch(err){fallback('三維展場無法啟動。');if(!ex){$('status').innerHTML='展覽資料未能載入。請確認以靜態伺服器開啟。<a href="collection.html">開啟完整作品目錄 ↗</a>';}}
}
document.querySelector('.skip').onclick=e=>{if(ex){e.preventDefault();showDialog('catalog-dialog');}};
boot();
