from pathlib import Path
import json
s={}
s['jelly-wave']=(Path(__file__).parent/'scenes'/f'jelly-wave.js').read_text()
s['pendulum-swing']=(Path(__file__).parent/'scenes'/f'pendulum-swing.js').read_text()
s['ribbon-dance']=(Path(__file__).parent/'scenes'/f'ribbon-dance.js').read_text()
s['bubble-scale']=(Path(__file__).parent/'scenes'/f'bubble-scale.js').read_text()
s['beat-candy']=(Path(__file__).parent/'scenes'/f'beat-candy.js').read_text()
s['tap-floor']=(Path(__file__).parent/'scenes'/f'tap-floor.js').read_text()
s['popcorn-rhythm']=(Path(__file__).parent/'scenes'/f'popcorn-rhythm.js').read_text()
s['hopscotch']=(Path(__file__).parent/'scenes'/f'hopscotch.js').read_text()
s['flower-choir']=(Path(__file__).parent/'scenes'/f'flower-choir.js').read_text()
s['canon-ripples']=(Path(__file__).parent/'scenes'/f'canon-ripples.js').read_text()
s['metronome-party']=(Path(__file__).parent/'scenes'/f'metronome-party.js').read_text()
s['signal-band']=(Path(__file__).parent/'scenes'/f'signal-band.js').read_text()
s['square-blocks']=(Path(__file__).parent/'scenes'/f'square-blocks.js').read_text()
s['saw-hills']=(Path(__file__).parent/'scenes'/f'saw-hills.js').read_text()
s['crayon-wave']=(Path(__file__).parent/'scenes'/f'crayon-wave.js').read_text()
s['spring-dancer']=(Path(__file__).parent/'scenes'/f'spring-dancer.js').read_text()
Path(__file__).with_name('scenes.json').write_text(json.dumps(s,ensure_ascii=False,indent=2))
print('16 scene scores compiled.')
