// Fixed track scales: real gestures, stable notes over musical time, and old ink remapping.
const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.SOUND_URL;
const expected={canon:[62,64,66,67,69,71,73,74],turkish:[57,59,60,62,64,65,67,69],hungarian:[55,57,58,60,62,63,65,67],bolero:[60,62,64,65,67,69,71,72],cancan:[60,62,64,65,67,69,71,72],william:[62,64,66,67,69,71,73,74]};
(async()=>{const b=await chromium.launch({headless:true}),results={checks:[],errors:[]};
for(const mobile of [false,true]){const p=await b.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:900},hasTouch:mobile,isMobile:mobile});p.on('pageerror',e=>results.errors.push(e.message));p.on('console',e=>{if(e.type()==='error')results.errors.push(e.text());});
await p.goto(base+'bubble-scale.html',{waitUntil:'networkidle'});await p.locator('#start').click();await p.waitForFunction(()=>soundState.playing);await p.locator('#backing').fill('0');
async function tap(x,y){const box=await p.locator('#art').boundingBox(),z=Math.min(box.width/1000,box.height/700),px=box.x+(box.width-1000*z)/2+x*z,py=box.y+(box.height-700*z)/2+y*z;if(mobile)await p.touchscreen.tap(px,py);else await p.mouse.click(px,py);await p.waitForTimeout(60);}
for(const [id,notes] of Object.entries(expected)){await p.locator('#track').selectOption(id);const pitches=[];for(let i=0;i<8;i++){await tap(110+(i+.5)*780/8,350);pitches.push(await p.evaluate(()=>soundState.interactiveMidi));}assert.deepEqual(pitches,notes);const label=await p.locator('#interaction-scale').textContent();assert(label.includes(id==='turkish'?'A 自然小調':id==='hungarian'?'G 自然小調':id==='canon'||id==='william'?'D 大調':'C 大調'));await p.evaluate(()=>Tone.Transport.ticks=4000);await p.waitForTimeout(180);await tap(110+3.5*780/8,350);assert.equal(await p.evaluate(()=>soundState.interactiveMidi),notes[3]);assert.equal(await p.locator('#interaction-scale').textContent(),label);const peak=await p.evaluate(()=>Math.max(...Array.from(soundAudio.analyser.getValue(),Math.abs)));assert(peak>.00001);results.checks.push({device:mobile?'mobile':'desktop',track:id,pitches,stableAcrossTime:true,peak});}
await p.goto(base+'crayon-wave.html',{waitUntil:'networkidle'});await p.locator('#track').selectOption('canon');await tap(400,300);const original=await p.evaluate(()=>soundScene.inspect().marks);assert(original.length);await p.locator('#track').selectOption('turkish');const remapped=await p.evaluate(()=>soundScene.inspect().marks);for(const mark of remapped)for(const pt of [...mark.points,...mark.notes])assert.equal(pt.midi,expected.turkish[Math.min(7,Math.max(0,Math.floor(Math.min(1,Math.max(0,(580-pt.y)/450))*8)))]);assert.notEqual(remapped[0].notes[0].midi,original[0].notes[0].midi);assert.equal(remapped[0].points[0].y,original[0].points[0].y);await p.locator('#start').click();await p.waitForFunction(()=>soundState.playing);await p.locator('#replay').click();await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>soundState.interactiveMidi),remapped[0].notes[0].midi);results.checks.push({device:mobile?'mobile':'desktop',inkRemapsAndReplays:true});await p.close();}
await b.close();assert.deepEqual(results.errors,[]);fs.writeFileSync(root+'/_qa/scale-results.json',JSON.stringify(results,null,2));console.log('PASS 96 pitched gestures, fixed scales over time, and 2 ink remap/replay cases');})().catch(e=>{console.error(e);process.exit(1)});
