/* Run with PLAYWRIGHT_MODULE set to the installed package if needed. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),works=JSON.parse(fs.readFileSync(path.join(__dirname,'works.json'))),base=process.env.SOUND_URL||'http://127.0.0.1:8765/sound/';
const result={date:new Date().toISOString(),checks:[],errors:[],resources:[],browser:null};
const initial=process.argv.includes('--thumbs'),only=(process.argv.find(a=>a.startsWith('--only='))||'').slice(7).split(',').filter(Boolean);
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--autoplay-policy=user-gesture-required']});result.browser=browser.version();
 for(const device of (initial?['desktop']:['desktop','mobile'])){
  const context=await browser.newContext({viewport:device==='desktop'?{width:1440,height:900}:{width:390,height:844},deviceScaleFactor:1,hasTouch:device==='mobile',isMobile:device==='mobile'});
  for(const work of works.filter(w=>!only.length||only.includes(w.slug))){
   const page=await context.newPage(),errors=[],bad=[];page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});page.on('response',r=>{if(r.status()>=400)bad.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>bad.push({url:r.url(),error:r.failure()?.errorText}));
   await page.goto(base+work.slug+'.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.soundState?.frames>2);await page.waitForTimeout(450);
   if(initial){await page.locator('canvas').screenshot({path:root+'/_qa/'+work.slug+'-canvas.png'});console.log('thumb '+work.slug);await page.close();continue;}
   const pixels=await page.evaluate(()=>{const c=document.querySelector('canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,s=new Set();for(let i=0;i<d.length;i+=124)s.add(`${d[i]},${d[i+1]},${d[i+2]}`);return s.size;});assert(pixels>12,work.slug+' blank canvas');
   assert(await page.evaluate(()=>!soundState.started),'must be silent before invitation');
   await page.locator('#start').click();await page.waitForFunction(()=>soundState.started&&soundState.playing);await page.waitForTimeout(1200);
   const audio=await page.evaluate(async()=>{let peak=0,begin=performance.now(),frames=soundState.frames;for(let j=0;j<12;j++){const a=window.soundAudio.analyser.getValue();peak=Math.max(peak,...Array.from(a,v=>Math.abs(v)));await new Promise(r=>setTimeout(r,50));}return{peak,fps:(soundState.frames-frames)*1000/(performance.now()-begin),notes:soundState.notes,context:Tone.getContext().state,version:Tone.version};});assert(await page.evaluate(()=>soundState.scoreTitle==='D 大調卡農'&&soundState.scoreEvents>0),'Canon score started');assert.equal(audio.context,'running');assert.equal(audio.version,'15.0.4');assert(audio.notes>0);assert(audio.peak>.00001,'no synthesized output '+work.slug);
   const c=page.locator('canvas'),box=await c.boundingBox();if(device==='mobile')await page.touchscreen.tap(box.x+box.width*.68,box.y+box.height*.55);else{await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.68,box.y+box.height*.55,{steps:8});await page.mouse.up();}
   assert(await page.evaluate(()=>soundState.interaction>0));await c.focus();const x=await page.evaluate(()=>soundState.x);await page.keyboard.press('ArrowLeft');assert((await page.evaluate(()=>soundState.x))<x);await page.keyboard.press('Enter');
   await page.locator('#tempo').fill('140');assert.equal(await page.evaluate(()=>soundState.tempo),140);
   await page.locator('#mute').click();assert(await page.evaluate(()=>soundState.muted));await page.waitForTimeout(400);const muted=await page.evaluate(()=>Math.max(...Array.from(soundAudio.analyser.getValue(),v=>Math.abs(v))));assert(muted<.00001,'mute not silent');await page.locator('#mute').click();
   await page.locator('#start').click();assert(!(await page.evaluate(()=>soundState.playing)));await page.locator('#start').click();assert(await page.evaluate(()=>soundState.playing));
   await page.locator('#motion').click();const stopped=await page.evaluate(()=>soundState.time);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>soundState.time),stopped);await page.locator('#motion').click();
   await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);const reducedTime=await page.evaluate(()=>soundState.time);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>soundState.time),reducedTime);assert(await page.evaluate(()=>soundState.reduced));await page.emulateMedia({reducedMotion:'no-preference'});
   await page.waitForTimeout(150);await page.locator('#tempo').fill(String(work.bpm));await page.screenshot({path:root+'/_qa/'+device+'-'+work.slug+'.png',fullPage:true});
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,work.slug+' horizontal overflow');
   result.checks.push({slug:work.slug,device,pixels,audio,touchOrDrag:true,keyboard:true,tempo:true,mute:true,pauseAndResume:true,reducedMotion:true,noOverflow:!overflow});result.errors.push(...errors.map(e=>({slug:work.slug,device,error:e})));result.resources.push(...bad.map(e=>({slug:work.slug,device,...e})));console.log('PASS '+device+' '+work.slug+' peak='+audio.peak.toFixed(5));await page.close();
  }
  if(!initial){const page=await context.newPage();page.on('pageerror',e=>result.errors.push({slug:'index',device,error:e.message}));page.on('console',e=>{if(e.type()==='error')result.errors.push({slug:'index',device,error:e.text()});});page.on('response',r=>{if(r.status()>=400)result.resources.push({slug:'index',device,url:r.url(),status:r.status()});});await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));const links=await page.locator('.card').evaluateAll(a=>a.map(e=>e.getAttribute('href')));assert.equal(links.length,16);for(const href of links){const r=await context.request.get(base+href);assert.equal(r.status(),200);}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:root+'/_qa/'+device+'-index.png',fullPage:true});result.checks.push({slug:'index',device,links:links.length,images:16,allLinks200:true,noOverflow:true});await page.close();}
  await context.close();
 }
 await browser.close();if(!initial){if(only.length&&fs.existsSync(root+'/_qa/results.json')){const previous=JSON.parse(fs.readFileSync(root+'/_qa/results.json'));result.checks=[...previous.checks.filter(c=>!only.includes(c.slug)&&c.slug!=='index'),...result.checks];result.errors=[...previous.errors.filter(c=>!only.includes(c.slug)&&c.slug!=='index'),...result.errors];result.resources=[...previous.resources.filter(c=>!only.includes(c.slug)&&c.slug!=='index'),...result.resources];}fs.writeFileSync(root+'/_qa/results.json',JSON.stringify(result,null,2));assert.equal(result.errors.length,0,JSON.stringify(result.errors));assert.equal(result.resources.length,0,JSON.stringify(result.resources));console.log('ALL 34 PAGE/VIEWPORT CHECKS PASSED');}
})().catch(e=>{fs.writeFileSync(root+'/_qa/failure.json',JSON.stringify({error:e.stack,result},null,2));console.error(e);process.exit(1);});
