import {MuseumWorld} from '../../js/world.js?v=entry-feedback-2';
import {startIntroTitle,finishIntroTitle} from '../../js/title.js?v=title-c-1';
const $=id=>document.getElementById(id),query=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');
let world,variant='a',busy=false,epoch=0,growth=null,completedView=null,reduced=query.matches;
function setReduced(value){reduced=value;document.body.classList.toggle('reduce-motion',value);$('motion').setAttribute('aria-pressed',String(value));$('motion').textContent=value?'動態已減少':'減少動態';if(world){world.reduced=value;reset();}if(value)finishIntroTitle();}
function reset(){epoch++;busy=false;growth?.resolve(false);growth=null;completedView=null;world?.resetEntryApproach();world?.pause(false);if(world?.entryFilm){world.entryFilm.mesh.scale.setScalar(1);world.entryFilm.elapsed=0;world.entryFilm.last=0;world.disturbEntryFilm(0);world.invalidate();}$('veil').classList.remove('active');document.querySelector('.after-fade').hidden=true;$('enter').removeAttribute('aria-busy');$('comparison-status').textContent='Hover 比較靠近感；點「進入展覽」看完整節奏。';}
function feedback(amount,duration=1000){if(!busy&&!reduced&&world)world.approachEntry(amount,duration);}
$('enter').addEventListener('pointerenter',()=>{if(fine.matches)feedback(1.8);});$('enter').addEventListener('pointerleave',()=>feedback(0,800));$('enter').addEventListener('pointercancel',()=>feedback(0,800));$('enter').addEventListener('pointerdown',()=>feedback(4.5,1250));$('enter').addEventListener('focus',()=>{if(fine.matches&&$('enter').matches(':focus-visible'))feedback(1.8);});$('enter').addEventListener('blur',()=>feedback(0,800));$('enter').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')feedback(4.5,1250);});
$('enter').onclick=async()=>{if(!world||busy)return;busy=true;const generation=++epoch;$('enter').setAttribute('aria-busy','true');finishIntroTitle();world.entryFilm.elapsed=0;world.entryFilm.last=0;world.disturbEntryFilm(0);const enlarged=variant==='b'&&!reduced?new Promise(resolve=>{growth={start:performance.now(),duration:1250,resolve};}):Promise.resolve(true);$('comparison-status').textContent=variant==='b'?'鏡頭前移，碟片同步緩慢放大至 120%。':'鏡頭前移，碟片保持原尺寸。';const complete=reduced||(await Promise.all([world.approachEntry(4.5,1250),enlarged])).every(Boolean);if(generation!==epoch||!complete)return;if(!reduced){if(variant==='b'){world.entryFilm.mesh.scale.setScalar(1.20);growth=null;world.invalidate();}await new Promise(r=>setTimeout(r,160));}if(generation!==epoch||document.hidden)return;completedView={offset:world.entryOffset,scale:world.entryFilm.mesh.scale.x};$('veil').classList.add('active');await new Promise(r=>setTimeout(r,reduced?0:250));if(generation!==epoch)return;world.pause(true);document.querySelector('.after-fade').hidden=false;$('comparison-status').textContent='完成。可切換版本，或按「再看一次」。';$('enter').removeAttribute('aria-busy');};
for(const button of document.querySelectorAll('[data-variant]'))button.onclick=()=>{variant=button.dataset.variant;reset();for(const b of document.querySelectorAll('[data-variant]'))b.setAttribute('aria-pressed',String(b===button));$('variant-description').textContent=variant==='a'?'只有鏡頭前移，碟片實際尺寸保持不變。':'Hover 同 A；click 才額外放大碟片 20%，鏡頭與淡出時間相同。';};
$('reset').onclick=reset;$('replay').onclick=()=>{reset();$('enter').focus({preventScroll:true});};$('motion').onclick=()=>setReduced(!reduced);query.addEventListener('change',e=>setReduced(e.matches));setReduced(reduced);
document.addEventListener('visibilitychange',()=>{if(document.hidden){reset();world?.pause(true);}else world?.pause(false);});
try{const response=await fetch('../../exhibition.json');if(!response.ok)throw Error('展覽資料載入失敗');const ex=await response.json();world=new MuseumWorld($('world'),ex,{reduced,onWork:()=>{},onStation:()=>{},onPortal:()=>{},onReady:()=>{$('status').textContent='真實入口場景 · 此頁只比較動效，不進入展廳。';},onFailure:message=>{$('status').textContent=message;$('enter').disabled=true;},onFrame:()=>{if(!growth)return;const t=Math.min(1,(performance.now()-growth.start)/growth.duration),u=t*t*(3-2*t);world.entryFilm.mesh.scale.setScalar(1+.20*u);if(t===1){const complete=growth.resolve;growth=null;complete(true);}}});Object.defineProperty(window,'discStudy',{get:()=>({variant,busy,completedView,scale:world.entryFilm?.mesh.scale.x,offset:world.entryOffset,moving:!!world.entryApproach,growing:!!growth,textures:world.renderer.info.memory.textures,geometries:world.renderer.info.memory.geometries,scheduled:!!world.raf})});startIntroTitle(()=>reduced);}catch(error){$('status').textContent=error.message;$('enter').disabled=true;}
