const fs=require('node:fs'),path=require('node:path');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const BASE=process.env.SOUND3_URL||'http://127.0.0.1:8766/sound3/',ROOT=path.resolve(__dirname,'..');const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await chromium.launch(),p=await b.newPage(),r={date:new Date().toISOString()};try{
await p.goto(BASE+'02-chord-loom.html');await p.locator('#play').click();await wait(1700);for(const i of [0,1,2])await p.locator(`[data-voice="${i}"]`).click();const time=await p.evaluate(()=>Sound3.state.time);await wait(1200);r.voicesOff=await p.evaluate(t=>({pass:Sound3.audio.level()<.002&&Sound3.state.time>t+.5&&Sound3.model.state.rows.slice(-2).every(r=>r.voices.every(v=>!v)),peak:Sound3.audio.level(),rows:Sound3.model.state.rows.length}),time);await p.locator('[data-voice="1"]').click();let restoredPeak=0;for(let k=0;k<22;k++){await wait(70);restoredPeak=Math.max(restoredPeak,await p.evaluate(()=>Sound3.audio.level()))}r.voiceBack=await p.evaluate(peak=>({pass:peak>1e-4&&Sound3.model.state.rows.at(-1).voices[1],peak}),restoredPeak);
await p.goto(BASE+'01-resonant-architecture.html');await p.locator('#play').click();await wait(9500);const old=await p.evaluate(()=>Sound3.model.state.arch.slice());await p.locator('#chord').selectOption('2');await wait(55);r.archContinuous=await p.evaluate(a=>({pass:Sound3.model.state.arch.every((v,i)=>Math.abs(v-a[i])<.15),before:a,after:Sound3.model.state.arch.slice()}),old);
await p.goto(BASE+'06-breath-portrait.html');await p.addInitScript(()=>Object.defineProperty(navigator,'mediaDevices',{value:undefined}));await p.reload();await p.locator('#microphone').click();await wait(550);r.noMicrophone={pass:await p.evaluate(()=>Sound3.state.mode==='demo'&&Sound3.state.playing)};
// External files are deliberately absent. Abort all non-local/audio file URLs
// and prove that the built-in composition still starts and emits a signal.
await p.route('**/*',route=>/\.(mp3|wav|ogg)(\?|$)/.test(route.request().url())?route.abort():route.continue());await p.goto(BASE+'08-stored-energy.html');await p.locator('#play').click();await wait(700);r.noMusicFiles={pass:await p.evaluate(()=>Sound3.state.playing&&Sound3.audio.notes>0&&Sound3.audio.level()>0)};
console.log(JSON.stringify(r,null,2));}finally{fs.writeFileSync(path.join(ROOT,'_qa','causal.json'),JSON.stringify(r,null,2));await b.close()}if(Object.values(r).some(v=>typeof v==='object'&&v.pass===false))process.exitCode=1})();
