const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.SOUND3_URL||'http://127.0.0.1:8766/sound3/';
(async()=>{const b=await chromium.launch(),result={date:new Date().toISOString(),base,pages:[],limitations:['Mobile browser emulation','No subjective listening','Synthetic microphone input']};try{
 for(const [device,viewport] of Object.entries({desktop:{width:1440,height:900},mobile:{width:390,height:844}})){
 const p=await b.newPage({viewport,isMobile:device==='mobile',hasTouch:device==='mobile'}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(base);const links=await p.locator('.card').evaluateAll(a=>a.map(x=>x.getAttribute('href')));
 for(const [i,file] of links.entries()){
 await p.goto(base+file);await p.waitForFunction(()=>window.Sound3);assert.equal(await p.evaluate(()=>!!Sound3.audio.ctx),false);const details=p.locator('details');await details.locator('summary').press('Space');assert.equal(await details.evaluate(d=>d.open),true);assert.equal(await p.evaluate(()=>Sound3.state.started),false);
 if(i===0){await p.locator('#tuning').evaluate(el=>{el.value='.7';el.dispatchEvent(new Event('input',{bubbles:true}))});await p.waitForFunction(()=>Sound3.state.playing);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>Sound3.params.manual),true);const shape=await p.evaluate(()=>Sound3.model.state.arch.slice()),time=await p.evaluate(()=>Sound3.state.time);await p.locator('[data-passage="1"]').click();await p.locator('#tuning').evaluate(el=>{el.value='-.7';el.dispatchEvent(new Event('input',{bubbles:true}))});await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>Sound3.params.passage),1);assert.notDeepEqual(await p.evaluate(()=>Sound3.model.state.arch),shape);assert(await p.evaluate(()=>Sound3.state.time)>time);assert(await p.evaluate(()=>Sound3.audio.level())>0.001);await p.locator('canvas').focus();await p.keyboard.press('ArrowRight');assert(await p.evaluate(()=>Sound3.params.tuning)>-.7);}
 if(i===1){await p.locator('#shuttle').click();await p.waitForFunction(()=>Sound3.model.state.manualRows===1);const count=await p.evaluate(()=>Sound3.model.state.rows.length),time=await p.evaluate(()=>Sound3.state.time);await p.locator('#weave').selectOption('2');assert.equal(await p.evaluate(()=>Sound3.model.state.rows.length),count);await p.locator('[data-voice="1"]').click();await p.locator('#shuttle').click();await p.waitForFunction(()=>Sound3.model.state.manualRows===2);const rows=await p.evaluate(()=>Sound3.model.state.rows);assert.equal(rows[0].voices[1],true);assert.equal(rows[1].voices[1],false);assert.equal(rows[0].weave,0);assert.equal(rows[1].weave,2);assert(await p.evaluate(()=>Sound3.state.time)>=time);
 const point=await p.evaluate(()=>{const r=document.querySelector('canvas').getBoundingClientRect(),u=Math.min(r.width/1100,r.height/650);return {left:r.x+r.width*.18,right:r.x+r.width*.82,y:r.y+r.height/2+Sound3.model.state.handle.y*u}});await p.mouse.move(point.left,point.y);await p.mouse.down();await p.mouse.move(point.right,point.y,{steps:15});await p.mouse.up();await p.waitForFunction(()=>Sound3.model.state.manualRows>=3);}
 if(i===2){await p.locator('#hold-sound').focus();await p.keyboard.down('Space');await p.waitForFunction(()=>Sound3.model.state.holding);await p.waitForTimeout(700);assert(await p.evaluate(()=>Sound3.audio.level())>0.001);await p.keyboard.up('Space');await p.waitForFunction(()=>Sound3.model.state.cuts.some(c=>c.manual));await p.waitForTimeout(2100);assert.equal(await p.evaluate(()=>Sound3.model.state.holding),false);assert(await p.evaluate(()=>Sound3.audio.level())<0.0002);const count=await p.evaluate(()=>Sound3.model.state.cuts.length);await p.locator('#mute').click();assert.equal(await p.evaluate(()=>Sound3.model.state.cuts.length),count);
 await p.locator('canvas').scrollIntoViewIfNeeded();const r=await p.locator('canvas').boundingBox();await p.mouse.move(r.x+r.width*.45,r.y+r.height*.3);await p.mouse.down();await p.waitForTimeout(700);await p.mouse.up();await p.waitForTimeout(2100);assert(await p.evaluate(()=>Sound3.model.state.cuts.length)>=2);}
 if(i===3){await p.locator('#play').click();if(device==='desktop'){await p.waitForFunction(()=>Sound3.model.state.complete,{},{timeout:38000})}else{await p.locator('#play').click();await p.evaluate(()=>Sound3.debug.stepTo(16))}const material=await p.evaluate(()=>Sound3.model.state.material.slice()),time=await p.evaluate(()=>Sound3.state.time);await p.locator('[data-layer="8"]').click();await p.waitForFunction(()=>Sound3.model.state.selectedLayer);await p.waitForTimeout(170);assert(await p.evaluate(()=>Sound3.audition.level())>.0001);assert(await p.evaluate(()=>Sound3.model.state.excavation.some(v=>v>0)));assert.deepEqual(await p.evaluate(()=>Sound3.model.state.material),material);assert.equal(await p.evaluate(()=>Sound3.state.time),time);await p.locator('#excavate-mode').click();const r=await p.locator('canvas').boundingBox();await p.mouse.move(r.x+r.width*.55,r.y+r.height*.43);await p.mouse.down();await p.mouse.move(r.x+r.width*.62,r.y+r.height*.48,{steps:10});await p.mouse.up();await p.locator('#restore-surface').click();assert(await p.evaluate(()=>Sound3.model.state.excavation.every(v=>v===0)));}
 if(i===4){await p.locator('#play').click();await p.waitForTimeout(200);const before=await p.evaluate(()=>Sound3.state.time);await p.locator('#phase-a').evaluate(el=>{el.value='.5';el.dispatchEvent(new Event('input',{bubbles:true}))});await p.locator('#delta').selectOption('2');await p.locator('#align-phases').click();await p.waitForTimeout(120);const phases=await p.evaluate(async()=>{const {phaseAt}=await import('./assets/js/interaction-model.js');return phaseAt(Sound3.params,Sound3.state.time)});assert(Math.abs(phases[0]-phases[1])<.02);assert(await p.evaluate(()=>Sound3.state.time)>before);assert.equal(await p.evaluate(()=>Sound3.params.delta),2);assert(await p.evaluate(()=>Sound3.audio.level())>.0001);
 const handle=await p.evaluate(()=>{const r=document.querySelector('canvas').getBoundingClientRect(),u=Math.min(r.width/1100,r.height/650),h=Sound3.model.state.phaseHandles[1];return {x:r.x+r.width/2+h.x*u,y:r.y+r.height/2+h.y*u}});await p.mouse.move(handle.x,handle.y);await p.mouse.down();await p.mouse.move(handle.x+35,handle.y,{steps:8});await p.mouse.up();assert(await p.evaluate(()=>Sound3.params.phaseControl[1])>0);}
 if(i===5){await p.locator('[data-breath="voice"]').click();await p.waitForTimeout(450);assert(await p.evaluate(()=>Sound3.model.state.breath.at(-1).r)>.1);await p.locator('[data-breath="airy"]').click();await p.waitForTimeout(350);assert(await p.evaluate(()=>Sound3.model.state.breath.at(-1).airy)>.9);await p.locator('[data-breath="pause"]').click();await p.waitForTimeout(800);assert.equal(await p.evaluate(()=>Sound3.model.state.complete),false);assert.equal(await p.locator('#breath-cue').textContent(),'停頓');await p.locator('#finish-breath').click();assert.equal(await p.evaluate(()=>Sound3.model.state.complete),true);await p.locator('[data-breath="voice"]').click();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>Sound3.model.state.gallery.length),1);}
 if(i===6){await p.locator('#ping').click();await p.waitForTimeout(1200);assert(await p.evaluate(()=>Sound3.model.state.paths.length)>0);const paths=await p.evaluate(()=>Sound3.model.state.paths.map(p=>p.path));await p.locator('#turn-gate').click();await p.locator('#ping').click();await p.waitForTimeout(1200);assert.notDeepEqual(await p.evaluate(()=>Sound3.model.state.paths.slice(-3).map(p=>p.path)),paths.slice(-3));const before=await p.evaluate(()=>Sound3.model.data.source.slice());await p.locator('[data-move="right"]').click();assert.notDeepEqual(await p.evaluate(()=>Sound3.model.data.source),before);await p.locator('canvas').focus();await p.keyboard.press('ArrowUp');assert(await p.evaluate(()=>Sound3.model.data.source[1])<before[1]);}
 if(i===7){await p.locator('#tap-energy').click();await p.waitForTimeout(300);assert(await p.evaluate(()=>Sound3.model.state.energy)>.1);const count=await p.evaluate(()=>Sound3.model.state.taps);await p.locator('#mode').selectOption('1');assert.equal(await p.evaluate(()=>Sound3.model.state.taps),count);await p.locator('#mode').selectOption('0');for(let k=0;k<5;k++){await p.locator('#tap-energy').click();await p.waitForTimeout(150)}assert(await p.evaluate(()=>Sound3.model.state.releases)>=1);await p.waitForTimeout(1000);}
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await details.locator('summary').click();await p.screenshot({path:path.join(root,'_qa/shots',`${device}-interactive-${i+1}.png`),fullPage:true});if(i===2)await p.locator('canvas').screenshot({path:path.join(root,'_qa/shots',`${device}-silence-new.png`)});
 if(await p.evaluate(()=>Sound3.state.playing)){await p.locator('#play').click();const time=await p.evaluate(()=>Sound3.state.time);await p.waitForTimeout(180);assert.equal(await p.evaluate(()=>Sound3.state.time),time);assert.equal(await p.evaluate(()=>Sound3.model.state.holding),false)}
 assert.deepEqual(errors,[]);result.pages.push({device,file,pass:true});console.log(device+' '+file+' passed');}
 await p.close();}
 result.pass=true;
 }catch(e){result.pass=false;result.error=e.stack;throw e}finally{fs.writeFileSync(path.join(root,'_qa/interactive-results.json'),JSON.stringify(result,null,2)+'\n');await b.close()}})();
