import baseAssert from 'node:assert/strict';
let checks=0;const assert=new Proxy(baseAssert,{apply(fn,self,args){checks++;return Reflect.apply(fn,self,args)},get(fn,key){const value=fn[key];return typeof value==='function'?function(...args){checks++;return Reflect.apply(value,fn,args)}:value}});
import {estimatePitch} from '../assets/js/audio.js';
import {createModel,echoScore,score,envelope} from '../assets/js/model.js';
function run(i,t,seed=4172,params={},dt=1/60){const m=createModel(i,seed,params);for(let x=dt;x<t+dt*.1;x+=dt)m.step(dt,x,[32,32,24,32,80,14,32,32][i],![3,5].includes(i));return m}
const a=run(3,32),b=run(3,32),c=run(3,32,8732);assert.deepEqual(a.state.material,b.state.material);assert.notDeepEqual(a.state.material,c.state.material);assert(a.state.complete);assert.deepEqual(a.state.material,run(3,32,4172,{},1/30).state.material);assert(a.state.layers.length<=96);
const arch=run(0,10);assert.equal(arch.state.chord,1);assert(run(0,6).state.stability>run(0,6,4172,{short:1}).state.stability+.2);
const loom=score(1,4172).events.filter(e=>e.kind==='weft');assert.deepEqual(loom.slice(0,16).map(e=>e.notes),loom.slice(16,32).map(e=>e.notes));assert.notDeepEqual(loom.slice(16,32).map(e=>e.notes),loom.slice(32,48).map(e=>e.notes));assert(run(1,64,4172,{voices:[true,false,true]}).state.rows.every(r=>r.voices[1]===false));assert(run(1,300).state.rows.length<=96);
const rests=score(2,4172).events.filter(e=>e.kind==='rest');assert(rests.some(e=>e.d>.65));assert(rests.some(e=>e.d===.65));assert(run(2,14).state.cuts.length>0);const cutHistory=run(2,14).state.cuts;assert(cutHistory.find(c=>c.d>2).prior>cutHistory.find(c=>c.d===.65).prior);
assert.notDeepEqual(run(5,14,4172,{demo:0}).state.breath,run(5,14,4172,{demo:1}).state.breath);assert(run(5,14).state.complete);assert(run(5,14).state.breath.length<=140);
const e=echoScore(4172),f=echoScore(4172,1);assert.notDeepEqual(e.events.filter(e=>e.kind==='echo').map(e=>e.t),f.events.filter(e=>e.kind==='echo').map(e=>e.t));const returns=e.events.filter(e=>e.kind==='echo');assert(returns.every(e=>e.t-e.pulse*4-.25>.001));assert(returns.every(e=>Math.abs((e.t-e.pulse*4-.25)-e.distance/8)<1e-8));for(const pulse of new Set(returns.map(e=>e.pulse))){const group=returns.filter(e=>e.pulse===pulse);assert(group.length<=3);assert(group.every((e,i)=>i===0||e.v<group[i-1].v))}assert(returns.some(e=>e.wall>=4));
const energy=run(7,20);assert(energy.state.releases>=1);const slow=run(7,20,4172,{mode:1});assert(slow.state.releases<=energy.state.releases);const long=run(7,600);assert(long.state.energy<=1.8);assert(long.state.releases<600/5);const longEcho=run(6,600);assert(longEcho.state.paths.length<=24);assert(longEcho.state.echoDistances.length<=24);
const energy30=run(7,18,4172,{},1/30);assert(Math.abs(energy30.state.energy-run(7,18).state.energy)<.05); // Integration agrees at independent steps.
const sr=48000,wave=Float32Array.from({length:2048},(_,i)=>Math.sin(i*2*Math.PI*220/sr)*.15),pitch=estimatePitch(wave,sr);assert(Math.abs(pitch.pitch-57)<.15);assert.equal(estimatePitch(new Float32Array(2048),sr).pitch,null);
console.log(JSON.stringify({pass:true,tests:checks,firstRelease:(()=>{const m=createModel(7);for(let t=1/60;t<=32;t+=1/60){m.step(1/60,t,32,true);if(m.state.releases)return t}return null})(),bounded600s:{rows:run(1,600).state.rows.length,echoPaths:longEcho.state.paths.length,energy:long.state.energy,releases:long.state.releases},fossilMaterialRange:[Math.min(...a.state.material),Math.max(...a.state.material)]},null,2));
