import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {notation} from '../assets/js/classical-notation.js';
import {classicalScore} from '../assets/js/classical.js';
const mapping={'can-can':'cancan',tell:'william'},beats={canon:32,prayer:20,elise:26.5,bolero:17.5,'can-can':25.5,turkish:16.5,tell:16.5,hungarian:25};let notes=0;const corrections=JSON.parse(readFileSync(new URL('../assets/js/classical-corrections.json',import.meta.url)));let applied=0;
for(const [id,score] of Object.entries(notation)){
 const ref=JSON.parse(readFileSync(new URL('../../sound/reusable/tracks/'+(mapping[id]||id)+'.json',import.meta.url))),groups=new Map();assert.equal(score.beats,beats[id]);assert.equal(score.ppq,ref.ppq);
 for(const [voiceIndex,voice] of ref.voices.entries()){if(voice.role==='percussion')continue;for(const [tick,sourceNote,length] of voice.events){if(tick>=beats[id]*ref.ppq)continue;let note=sourceNote;for(const correction of corrections){if(correction.id===id&&correction.referenceVoice===voiceIndex&&correction.tick===tick&&correction.from===note){note=correction.to;applied++}}const part=voice.role==='bass'||id==='prayer'&&note<60?'bass':'melody',clipped=Math.min(length,beats[id]*ref.ppq-tick),key=JSON.stringify([tick,clipped,part]);if(!groups.has(key))groups.set(key,new Set());groups.get(key).add(note)}}
 const actual=new Map(score.events.map(([tick,length,pitches,part])=>[JSON.stringify([tick,length,part]),new Set(pitches)]));assert.deepEqual(actual,groups);
 for(const duration of [14,16,24,32,240]){const unit=(duration-.45)/beats[id],events=classicalScore(id,duration).filter(e=>e.part==='melody'||e.part==='bass');assert.equal(events.length,score.events.length);for(const [i,[tick,length,pitches,part]] of score.events.entries()){const e=events.find(e=>e.beat===tick/ref.ppq&&e.part===part&&JSON.stringify(e.notes)===JSON.stringify(pitches)&&Math.abs(e.d-Math.min(Math.max(.05,length/ref.ppq*unit),duration-(.12+tick/ref.ppq*unit)-.1))<1e-8);assert(e,id+' note not preserved');assert.equal(e.t,.12+tick/ref.ppq*unit);assert.equal(e.voice,'piano');assert.equal(e.v,part==='melody'?.34:.16);notes+=pitches.length}}
}
assert.equal(applied,corrections.length);assert.deepEqual(classicalScore('can-can').find(e=>e.part==='melody'&&e.beat===13.5).notes,[69]);assert.deepEqual(classicalScore('tell').find(e=>e.part==='melody'&&e.beat===6.5).notes,[61]);const result={pass:true,verifiedCorrections:applied,tracks:8,noteChecks:notes,correctedReferencePitchOnsetDurationParity:true,existingTempoConversionPreserved:true,existingVoicesAndLevelsPreserved:true};writeFileSync(new URL('../_qa/notation-results.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
