import {works,playGuides} from '../assets/js/catalog.js';
import {writeFileSync} from 'node:fs';
const root=new URL('../',import.meta.url);
const controls=[
 `<label class="sr-only" for="chord">和弦／空間</label><select id="chord" data-param="chord"><option value="">和弦慢慢巡遊</option><option value="0">明亮 · C 大調</option><option value="1">懸念 · A 小調九度</option><option value="2">開闊 · F 開放和弦</option><option value="3">未定 · G 掛留</option></select><label class="sr-only" for="short">持續時間</label><select id="short" data-param="short"><option value="0">長音凝聚</option><option value="1">短音鬆動</option></select>`,
 `<label class="sr-only" for="weave">織法</label><select id="weave" data-param="weave"><option value="0">平織</option><option value="1">斜紋</option><option value="2">疏織</option></select><div class="voices" aria-label="聲部開關"><button data-voice="0" aria-pressed="true">低音</button><button data-voice="1" aria-pressed="true">旋律</button><button data-voice="2" aria-pressed="true">節點</button></div>`,
 `<label class="sr-only" for="space">留白程度</label><select id="space" data-param="space"><option value="0">克制的留白</option><option value="1">讓沉默更深</option></select>`,
 `<button id="regenerate">留下另一件標本</button><span class="help">拖曳／方向鍵旋轉</span>`,
 `<label class="sr-only" for="delta">相位速度差</label><select id="delta" data-param="delta"><option value="0">靠近 · 120 秒</option><option value="1" selected>潮汐 · 80 秒</option><option value="2">離開 · 60 秒</option></select>`,
 `<label class="sr-only" for="demo">示範氣息</label><select id="demo" data-param="demo"><option value="0">延伸 · 長氣息</option><option value="1">斷續 · 五段短句</option><option value="2">迴旋 · 逐漸升高</option></select><button id="microphone" aria-pressed="false">用我的聲音</button>`,
 `<button id="ping">發出一個聲音</button><label class="sr-only" for="origin">回聲起點</label><select id="origin" data-param="origin"><option value="0">西側起點</option><option value="1">東側起點</option></select>`,
 `<label class="sr-only" for="mode">蓄能模式</label><select id="mode" data-param="mode"><option value="0">脆弱 · 較早翻開</option><option value="1">穩定 · 慢慢蓄能</option></select>`
];
const guide=(i)=>`<details class="how-to-play"><summary>How to play <span>玩法說明</span></summary><div class="play-guide"><ol>${playGuides[i].steps.map(step=>`<li>${step}</li>`).join('')}</ol><div class="guide-notes"><p>${playGuides[i].watch}</p><p class="common-guide">共通操作：暫停會停住展演；靜音只關閉聲音，畫面繼續。重播從頭開始，存圖保存目前畫面。展開或收合此說明不會影響展演。</p></div></div></details>`;
const head=(title,desc)=>`<!doctype html>\n<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${desc}"><meta name="theme-color" content="#f4f1e9"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><title>${title}｜聲音成為物質 SOUND / 3</title><link rel="stylesheet" href="assets/css/exhibition.css"></head>`;
for(const [i,w] of works.entries()){
const n=String(i+1).padStart(2,'0'),prev=works[(i+7)%8],next=works[(i+1)%8];
writeFileSync(new URL(w.id+'.html',root),head(w.name,w.text)+`<body data-work="${i}"><header class="mast"><a class="brand" href="index.html">SOUND / 3　聲音成為物質</a><span>八件聲音與能量的研究</span></header><main><div class="work-head"><div><p class="eyebrow">${n} / 08　${w.en}</p><h1>${w.name}</h1><p class="subtitle">《${w.title}》</p></div><p class="description">${w.text}</p></div><section class="stage ${[2,3,6].includes(i)?'dark':''}" aria-label="${w.name}展演場域"><canvas tabindex="0" aria-label="${w.name}生成作品${[3,5].includes(i)?'，拖曳或方向鍵旋轉':''}">此瀏覽器不支援畫布。請欣賞<a href="assets/previews/${w.id}.webp">作品代表畫面</a>。</canvas><span class="label">${w.material}　/　<span id="elapsed" class="elapsed">00″</span></span><span id="caption" class="caption">靜態預展</span></section><div class="controls" aria-label="展演控制"><button id="play" class="primary" aria-pressed="false">開始聆聽</button><button id="replay">重播</button><button id="mute" aria-pressed="false">靜音</button><label class="volume">音量<input id="volume" aria-label="音量" type="range" min="0" max="1" step="0.05" value="0.45"></label><button id="export">存圖 PNG</button><div class="special">${controls[i]}</div></div>${guide(i)}</main><footer class="foot"><div><div id="notice" role="status">原創程式作曲 · 按下開始後才啟動聲音。</div><div>聲音與生成：SOUND / 3 · <a href="MUSIC_CREDITS.md">音源與授權</a>${[0,6].includes(i)?' · 創作性聲學模型':''}</div></div><nav aria-label="作品導覽"><a href="${prev.id}.html">← 上一件</a><a href="index.html">展覽目錄</a><a href="${next.id}.html">下一件 →</a></nav></footer><script type="module" src="assets/js/core.js"></script></body></html>\n`);
}
writeFileSync(new URL('index.html',root),head('聲音成為物質','聲音如何形成空間、材料、記憶與事件。八件原創視聽生成作品。')+`<body><header class="mast"><a class="brand" href="index.html">SOUND / 3</a><span>聲音・空間・能量</span></header><main><section class="hero"><div><p class="eyebrow">AN EXHIBITION IN EIGHT MOVEMENTS</p><h1>聲音成為物質<span>聽見之後，留下什麼？</span></h1><p class="edition">GENERATIVE SOUND ART　/　2026　/　第三輯</p></div><p class="intro">聲音可以是一座建築、一匹布、一道切口，或一件記得旋律的標本。<br>八個房間，八種時間。在這裡，耳朵看見空間，沉默留下形狀。<br><br>選一件作品。按下開始聆聽，讓聲音慢慢形成。</p></section><section class="gallery" aria-label="八件作品">${works.map((w,i)=>`<a class="card" href="${w.id}.html"><div class="image"><img src="assets/previews/${w.id}.webp" alt="${w.name}實際生成畫面：${w.material}" width="1100" height="650" ${i>1?'loading="lazy"':''}></div><div class="meta"><h2><span class="number">${String(i+1).padStart(2,'0')}</span>${w.name}</h2><span class="en">${w.en} ↗</span></div><p class="title">《${w.title}》</p><p class="invitation">${w.text}</p></a>`).join('')}</section></main><footer class="index-foot"><p>每一頁都有自己的聲音。<br>所有預設音源為原創程式作曲；不需麥克風即可完整觀看。</p><p><a href="MUSIC_CREDITS.md">音源與授權</a><br><a href="../sound2/">上一輯 SOUND / 2</a>　／　<a href="../magazine2/">間物 BETWEEN MATTER</a></p></footer></body></html>\n`);
