const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const base=process.env.SOUND3_BASE||'http://127.0.0.1:8766/sound3/',out=process.env.SOUND3_REQUEST_RESULT||path.join(__dirname,'../_qa/request-results.json');
const ids=['01-resonant-architecture','02-chord-loom','03-silence-cuts','04-sound-fossil','05-phase-tides','06-breath-portrait','07-echo-labyrinth','08-stored-energy'],tracks=['canon','prayer','elise','bolero','can-can','turkish','tell','hungarian'];
(async()=>{const browser=await chromium.launch({headless:true}),results=[],errors=[];try{
 for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile}),page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(base+ids[2]+'.html');await page.waitForFunction(()=>window.Sound3);await page.locator('#hold-sound').focus();await page.keyboard.down('Space');await page.waitForFunction(()=>Sound3.model.state.holding);await page.waitForTimeout(150);const first=await page.locator('canvas').screenshot();await page.waitForTimeout(1800);const second=await page.locator('canvas').screenshot();assert(!first.equals(second));assert(await page.evaluate(()=>!!Sound3.model.state.pressCut));await page.screenshot({path:path.join(path.dirname(out),`hold-${mobile?'mobile':'desktop'}.png`),fullPage:true});await page.keyboard.up('Space');assert(await page.evaluate(()=>Sound3.model.state.cuts.some(c=>c.manual)&&!Sound3.model.state.pressCut));await page.locator('#hold-sound').focus();await page.keyboard.down('Space');await page.waitForFunction(()=>Sound3.model.state.holding);const cuts=await page.evaluate(()=>Sound3.model.state.cuts.length);await page.evaluate(()=>document.querySelector('#play').click());await page.keyboard.up('Space');assert.equal(await page.evaluate(()=>Sound3.model.state.cuts.length),cuts);assert.equal(await page.evaluate(()=>Sound3.model.state.pressCut),null);results.push({device:mobile?'mobile':'desktop',holdGrowth:true,cancelDoesNotCommit:true});
 await page.goto(base+ids[3]+'.html');await page.waitForFunction(()=>window.Sound3);assert.equal(await page.locator('#fossil-progress').getAttribute('max'),'16');await page.locator('#play').click();await page.waitForTimeout(1800);assert((await page.locator('#fossil-remaining').textContent()).includes('剩餘'));await page.locator('#play').click();const paused=await page.evaluate(()=>document.querySelector('#fossil-progress').value);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.querySelector('#fossil-progress').value),paused);await page.locator('#play').click();await page.waitForFunction(()=>Sound3.model.state.complete,{},{timeout:18000});assert.equal(await page.evaluate(()=>Sound3.state.playing),false);assert.equal(await page.evaluate(()=>document.querySelector('#fossil-progress').value),16);assert.equal(await page.locator('[data-layer="8"]').isEnabled(),true);await page.screenshot({path:path.join(path.dirname(out),`fossil-${mobile?'mobile':'desktop'}.png`),fullPage:true});await page.locator('[data-layer="8"]').click();await page.waitForTimeout(200);assert(await page.evaluate(()=>Sound3.model.state.excavation.some(x=>x>0)));results.push({device:mobile?'mobile':'desktop',fossilCompletesAt16:true,pausedProgressStable:true,excavation:true});await context.close();
 }
 for(let index=0;index<8;index++){const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(String(e)));await page.goto(base+ids[index]+'.html');await page.waitForFunction(()=>window.Sound3);assert.equal(await page.locator('#soundtrack option').count(),9);assert.equal(await page.locator('.technology').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#soundtrack').selectOption('canon');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>Sound3.audio.ctx),null);assert.equal(await page.locator('details').getAttribute('open'),null);for(const track of tracks){await page.locator('#soundtrack').selectOption(track);await page.waitForTimeout(80);if(!(await page.evaluate(()=>Sound3.state.playing)))await page.locator('#play').click();let peak=0;for(let k=0;k<18;k++){await page.waitForTimeout(120);peak=Math.max(peak,await page.evaluate(()=>Sound3.audio.level()))}assert(peak>.0005,`${index}/${track} inaudible ${peak}`);assert.equal(await page.evaluate(()=>Sound3.params.soundtrack),track);results.push({work:index+1,track,peak})}console.log(ids[index]+" / eight tracks passed");await page.close()}
 assert.deepEqual(errors,[]);fs.writeFileSync(out,JSON.stringify({pass:true,base,checks:results.length,results,errors},null,2)+'\n');console.log(JSON.stringify({pass:true,checks:results.length,base}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
