const BASE=process.env.INTERVAL_URL||'http://localhost:8000/interval/';
const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=require('path').resolve(__dirname,'../..'),ex=JSON.parse(fs.readFileSync(root+'/interval/exhibition.json','utf8'));
const out={environment:{platform:process.platform,playwright:require((process.env.PLAYWRIGHT_MODULE||'playwright')+'/package.json').version},inventory:[],works:[],checks:[],errors:[]};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function ready(p){await p.waitForFunction(()=>window.intervalState?.render&&(!window.intervalState.render.scheduled||window.intervalState.render.ambient)&&!window.intervalState.render.moving&&!window.intervalState.render.pending&&getComputedStyle(document.querySelector('#veil')).opacity==='0');}
async function focus(p,w){await p.locator('#list-button').click();await p.locator('#search').fill(w.name);await p.locator('.catalog-work').filter({has:p.getByRole('heading',{name:w.name,exact:true})}).getByRole('button').click();await ready(p);}
async function open(p,w){await focus(p,w);await p.locator('#open-work').click();await p.locator('iframe').waitFor();const frame=p.frames().find(f=>f.parentFrame());await frame.waitForSelector('canvas');await p.waitForFunction(()=>document.querySelector('#viewer-status').hidden);return frame;}
async function canvasHash(frame){const canvas=frame.locator('canvas').first();return hash(await canvas.screenshot());}
async function input(frame){
 const ranges=frame.locator('input[type=range]');let actions=[];
 if(await ranges.count()){const r=ranges.first();await r.evaluate(e=>{const min=Number(e.min||0),max=Number(e.max||1);e.value=String(min+(max-min)*.8);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));});actions.push('滑桿至80%');}
 const canvas=frame.locator('canvas').first();await canvas.click();await canvas.press('ArrowRight');await canvas.press('Enter');actions.push('畫布點擊、方向鍵與Enter');return actions;
}
(async()=>{assert.equal(ex.works.length,35);assert.equal(new Set(ex.works.map(w=>w.id)).size,35);for(const series of ['p5-demos2','shader-demos2']){const actual=fs.readdirSync(root+'/'+series).filter(n=>n.endsWith('.html')&&!n.includes('demo-list'));const curated=ex.works.filter(w=>w.series===series);assert.equal(actual.length,curated.length);for(const w of curated){assert(actual.includes(w.slug+'.html'));assert(fs.existsSync(root+'/interval/'+w.preview));assert(fs.existsSync(root+'/interval/'+w.source));assert(w.selfStatement&&w.placement&&w.entry);out.inventory.push(w.id);}}
 const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader']});out.environment.browser=b.version();out.environment.renderer='SwiftShader';out.environment.viewports=['1440×900 desktop','390×844 touch/mobile emulation'];
 const ctx=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});const p=await ctx.newPage();p.on('pageerror',e=>out.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)out.errors.push(r.status()+' '+r.url());});await p.goto(BASE);await ready(p);assert.equal(await p.locator('#motion').getAttribute('aria-pressed'),'true');out.checks.push('system reduced-motion detected');
 const previous=process.env.INTERVAL_RESUME==='1'?JSON.parse(fs.readFileSync(root+'/interval/qa-results.json','utf8')):{works:[]};out.works=previous.works.filter(w=>w.pass);for(const w of ex.works){if(out.works.some(r=>r.id===w.id))continue;const result={id:w.id,series:w.series,section:w.section,name:w.name};try{const frame=await open(p,w);result.url=frame.url();assert(new URL(result.url).pathname.endsWith('/'+w.series+'/'+w.slug+'.html'));await frame.waitForTimeout(w.series==='p5-demos2'?900:350);const before=await canvasHash(frame);result.canvasCount=await frame.locator('canvas').count();result.activeIframes=await p.locator('iframe').count();assert.equal(result.activeIframes,1);result.actions=await input(frame);
 if(w.slug==='within-the-same-frame'){await frame.locator('canvas').first().press('ArrowRight');await frame.locator('canvas').first().press('Enter');const level=await frame.locator('#level').textContent();result.level=level;await frame.locator('#top').click();result.returnLevel=await frame.locator('#level').textContent();assert(result.returnLevel.includes('1 / 5'));}
 if(w.series==='shader-demos2'){const button=frame.locator('button[data-param]').first();if(await button.count()){await button.click();result.actions.push('原作參數按鈕');}if(w.slug==='thin-film'){await frame.locator('[data-param=detail]').click();result.detail=await frame.locator('[data-param=detail]').getAttribute('aria-pressed');assert.equal(result.detail,'true');}}
 if(await frame.locator('#regen').count()){const oldSeed=await frame.locator('#seed').textContent();await frame.locator('#regen').click();await frame.waitForTimeout(200);result.regenerated=(await frame.locator('#seed').textContent())!==oldSeed;assert(result.regenerated);result.actions.push('重新生成新種子');}
 await frame.waitForTimeout(250);const after=await canvasHash(frame);result.imageChanged=before!==after;
 if(await frame.locator('#reset').count()){await frame.locator('#reset').click();result.actions.push('回到初始');}
 if(await frame.locator('#fallback').count()){result.fallbackVisible=await frame.locator('#fallback').isVisible();assert(!result.fallbackVisible);}
 const returnBefore=await p.evaluate(()=>window.intervalState.position);await p.locator('#viewer-close').click();await ready(p);const returnAfter=await p.evaluate(()=>window.intervalState.position);assert.deepStrictEqual(returnAfter,returnBefore);assert.equal(await p.locator('iframe').count(),0);result.returnPreserved=true;result.pass=true;
 }catch(e){result.pass=false;result.error=e.message;console.log('FAILED',w.name,e.message);if(await p.locator('#viewer').evaluate(d=>d.open))await p.locator('#viewer-close').click();}out.works.push(result);console.log(JSON.stringify(result));fs.writeFileSync(root+'/interval/qa-results.json',JSON.stringify(out,null,2));}
 // Navigation and original-page link switching keep the initial return position.
 const first=ex.works.find(w=>w.slug==='negotiated-territories');const f=await open(p,first);const returnOrigin=await p.evaluate(()=>window.intervalState.position);await f.locator('.pn .next').click();await p.waitForFunction(()=>window.intervalState.viewer?.includes('registration-pending'));await p.waitForFunction(()=>document.querySelector('#viewer-status').hidden);await p.locator('#viewer-close').click();assert.deepStrictEqual(await p.evaluate(()=>window.intervalState.position),returnOrigin);out.checks.push('original next-work link intercepted; return location preserved');
 const repeated=[];for(let i=0;i<8;i++){const f=await open(p,first);await p.locator('#viewer-close').click();await ready(p);repeated.push(await p.evaluate(()=>({frames:document.querySelectorAll('iframe').length,canvases:document.querySelectorAll('canvas').length,memory:window.intervalState.render})));}assert(repeated.every(n=>n.frames===0&&n.canvases===1));assert(new Set(repeated.map(n=>n.memory.textures)).size===1);out.repeated=repeated;out.checks.push('8 repeated viewer cycles: 0 remaining iframe, 1 gallery canvas, stable renderer textures/geometries');
 // Walk every station through every room with actual UI arrows.
 await p.locator('#home').click();await ready(p);await p.locator('#enter').click();await ready(p);let path=[];for(let room=1;room<=5;room++){const n=ex.works.filter(w=>w.section===room).length;for(let i=0;i<n+1;i++){await p.locator('#next-stop').click();await ready(p);path.push(await p.evaluate(()=>({room:window.intervalState.current,station:window.intervalState.station})));}if(room<5){await p.locator('#next-stop').click();await ready(p);}}assert(await p.locator('#ending').isVisible());await p.locator('#next-stop').click();await ready(p);assert.equal((await p.evaluate(()=>window.intervalState)).current,1);out.path=path;out.checks.push('complete desktop route through all 35 artwork stations and ending');
 await p.locator('#home').click();await ready(p);await p.locator('#intro-tour').click();await ready(p);assert(await p.locator('#tourbar').isVisible());await p.locator('#tour-pause').click();assert((await p.evaluate(()=>window.intervalState.tour)).paused);for(let i=0;i<9;i++){await p.locator('#tour-next').click();await ready(p);}assert.equal((await p.evaluate(()=>window.intervalState.tour)).index,9);await p.locator('#tour-exit').click();assert(!(await p.locator('#tourbar').isVisible()));out.checks.push('guided tour: start, pause, all 10 stops via skip, exit');
 await p.locator('#map-button').click();await p.locator('.map-room').nth(1).click();await ready(p);await focus(p,ex.works.find(w=>w.slug==='within-the-same-frame'));assert.equal(await p.locator('#portal').count(),0);assert.equal(await p.locator('#room-controls button').count(),3);out.checks.push('recursive-door work: standard three-button controls; original work remains accessible');
 await p.locator('#list-button').click();await p.locator('#search').fill('no-such-artwork');assert(await p.locator('#empty').isVisible());await p.locator('#search').fill('');await p.locator('#filters button').nth(3).click();assert.equal(await p.locator('.catalog-work').count(),7);await p.locator('#filters button').first().click();assert.equal(await p.locator('.catalog-work').count(),35);await p.locator('#catalog-dialog [data-close]').click();out.checks.push('catalogue search, empty state, section filter, reset to 35');
 await p.close();await ctx.close();
 // Mobile emulation: the entire path, touching the artwork and returning to the same spot.
 const mc=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce',deviceScaleFactor:2});const m=await mc.newPage();m.on('pageerror',e=>out.errors.push('mobile '+e.message));await m.goto(BASE);await ready(m);await m.locator('#enter').tap();await ready(m);for(let room=1;room<=5;room++){const n=ex.works.filter(w=>w.section===room).length;for(let i=0;i<n+1;i++){await m.locator('#next-stop').tap();await ready(m);}if(room<5){await m.locator('#next-stop').tap();await ready(m);}}assert(await m.locator('#ending').isVisible());await m.locator('#next-stop').tap();await ready(m);assert.equal((await m.evaluate(()=>window.intervalState)).current,1);assert(await m.evaluate(()=>document.documentElement.scrollWidth===innerWidth));out.checks.push('390×844 DPR2 touch emulation: complete 35-station route, ending, no horizontal overflow');
 const mf=await open(m,ex.works.find(w=>w.slug==='within-the-same-frame'));await mf.locator('canvas').first().tap({position:{x:70,y:70}});await mf.locator('#reset').tap();await m.locator('#viewer-close').tap();assert.equal(await m.locator('iframe').count(),0);out.checks.push('mobile original-work touch and close');await mc.close();
 await b.close();fs.writeFileSync(root+'/interval/qa-results.json',JSON.stringify(out,null,2));console.log('FINAL',JSON.stringify({works:out.works.length,passed:out.works.filter(w=>w.pass).length,checks:out.checks,errors:out.errors},null,2));assert.equal(out.works.filter(w=>w.pass).length,35);assert.equal(out.errors.length,0);})();
